---
groups:
- name: prometheus_base
  rules:
  - alert: AlwaysAlert
    annotations:
      message: |
        This is an alert meant to ensure that the entire alerting pipeline is functional.
        This alert is always firing, therefore it should always be firing in Alertmanager
        and always fire against a receiver.  We use cronitor to alert us if this ever
        *doesn't* fire, because this indicates a problem with our alerting pipeline
    expr: vector(1)
    labels:
      severity: "constant"
- name: service
  rules:
  - alert: HubSamlProxyNonEidasErrorRate
    labels:
      severity: "p1"
    annotations:
      message: |
        It looks like users are having trouble with SAML interactions
        in their journeys at the hub.  This means that they will be
        unable to complete their journeys.  We expect that the
        saml-proxy endpoints should return a 2xx response under normal
        conditions.  We are observing the rate of 2xx responses has
        dropped below 95%.
    expr: |
      sum without(instance)(
            rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageReceiverApi_handleRequestPost_2xx_responses_total[15m])
          + rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageReceiverApi_handleResponsePost_2xx_responses_total[15m])
          + rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageSenderApi_sendJsonAuthnRequestFromHub_2xx_responses_total[15m])
          + rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageSenderApi_sendJsonAuthnResponseFromHub_2xx_responses_total[15m]))
      / sum without(instance)(
            rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageReceiverApi_handleRequestPost_count[15m])
          + rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageReceiverApi_handleResponsePost_count[15m])
          + rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageSenderApi_sendJsonAuthnRequestFromHub_count[15m])
          + rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageSenderApi_sendJsonAuthnResponseFromHub_count[15m]))

          < 0.95

  - alert: EveryMsaIsUnhealthy
    labels:
      severity: "p1"
    annotations:
      message: |
        We run regular MSA healthchecks.  It looks like every single
        MSA is unhealthy.  This will mean that users are unable to
        complete journeys at the hub and probably indicates a problem
        with the hub rather than with any corresponding MSA.
    expr: |
      sum(verify_saml_soap_proxy_msa_health_status) < 1
